@startuml
enum CommandFlag {
    Exit= 0,
    CreatePassword= 10,
    CreatePasswordGenerated= 11,
    GetPassword= 12,
    GetAllPasswords= 13,
    UpdatePassword= 14,
    UpdatePasswordGenerated= 15,
    DeletePassword= 16,
    DeleteAllPasswords= 17,
    SearchPasswordEntries= 18,
    CreateVault= 20,
    BackupVault= 21,
    RestoreVault= 22,
    DeleteVault= 23,
    UpdateMasterPassword= 30,
}
@enduml
