@startuml
class GetAllPasswordsCommand {
    - <<const>> infoMessage : string = "A healthy password should be unique within the vault, at least 8 characters long, and contain at least one uppercase letter, one lowercase letter, and one digit."
    - <<const>> errorMessage : string = "No password entries found."
    + GetAllPasswordsCommand(vault:IVault, consoleService:IConsoleService)
    + Execute() : void
    - {static} GetPasswordHealthDescription(passwordHealthResult:PasswordHealthResult) : string
}
ICommand <|-- GetAllPasswordsCommand
GetAllPasswordsCommand --> "vault" IVault
GetAllPasswordsCommand --> "consoleService" IConsoleService
GetAllPasswordsCommand --> "passwordHealthService" PasswordHealthService
@enduml
