@startuml
class GetPasswordCommand {
    - <<readonly>> serviceNamePrompt : string = "Enter the service name: "
    - <<readonly>> accountNamePrompt : string = "Enter the account name: "
    - <<readonly>> errorEmptyInputMessage : string = "Service name and account name cannot be empty."
    - <<readonly>> passwordInfoMessage : string = "Information for {0&#125;, {1&#125;:"
    - <<readonly>> passwordNotFoundMessage : string = "No password entry found for service {0&#125;, account {1&#125;."
    - <<readonly>> warningMessage : string = "This password is not healthy. A healthy password should be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, one digit and be unique inside this Vault."
    - <<readonly>> passwordHealthyMessage : string = "This password is healthy."
    + GetPasswordCommand(vault:IVault, consoleService:IConsoleService)
    + Execute() : void
    - GetServiceName() : string
    - GetAccountName() : string
    - WritePasswordInfo(passwordEntry:Domain.Entities.PasswordEntry, serviceName:string, accountName:string) : void
}
ICommand <|-- GetPasswordCommand
GetPasswordCommand --> "vault" IVault
GetPasswordCommand --> "consoleService" IConsoleService
GetPasswordCommand --> "passwordHealthService" PasswordHealthService
@enduml
