@startuml
class SearchPasswordEntriesCommand {
    - <<readonly>> searchPrompt : string = "Enter your search query: "
    - <<readonly>> matchingEntriesMessage : string = "Matching search entries:"
    - <<readonly>> noEntriesFoundError : string = "No matching entries found."
    + Execute() : void
    - GetMatchingEntriesDataRows(matchingEntries:IEnumerable<Domain.Entities.PasswordEntry>) : List<List<object>>
}
ICommand <|-- SearchPasswordEntriesCommand
@enduml
