@startuml
class PasswordEntryBuilder {
    + SetServiceName(serviceName:string) : PasswordEntryBuilder
    + SetAccountName(accountName:string) : PasswordEntryBuilder
    + SetEncryptedPassword(encryptedPassword:string) : PasswordEntryBuilder
    + SetUrl(url:string) : PasswordEntryBuilder
    + SetCategory(category:string) : PasswordEntryBuilder
    + Build() : PasswordEntry
}
PasswordEntryBuilder o-> "_passwordEntry" PasswordEntry
@enduml
