@startuml
class VaultFactory {
    - <<const>> VaultFilePath : string = "vault.dat"
    - <<const>> MasterPasswordFilePath : string = "masterpassword.dat"
    + CreateVault(masterPassword:string) : IVault?
    + DeleteVault() : bool
    + GetVault() : IVault
}
IVaultFactory <|-- VaultFactory
VaultFactory --> "_vault" IVault
VaultFactory o-> "vaultConsoleService" IConsole
VaultFactory o-> "vaultEncryptionService" IVaultEncryptionService
VaultFactory o-> "vaultFileService" IVaultFileService
VaultFactory o-> "vaultPasswordGenerator" IVaultPasswordGenerator
@enduml
