@startuml
class CreatePasswordCommand {
    - <<readonly>> serviceNamePrompt : string = "Enter service name for the new password: "
    - <<readonly>> accountNamePrompt : string = "Enter account name for the new password: "
    - <<readonly>> passwordPrompt : string = "Enter the password: "
    - <<readonly>> urlPrompt : string = "Enter the URL (leave empty if not applicable): "
    - <<readonly>> categoryPrompt : string = "Enter the category (leave empty if not applicable): "
    - <<readonly>> successMessage : string = "A new password has been created and stored for {0&#125;, {1&#125;."
    + Execute() : void
}
ICommand <|-- CreatePasswordCommand
@enduml
