@startuml
class CreatePasswordCommand {
    - <<const>> serviceNamePrompt : string = "Enter service name for the new password: "
    - <<const>> accountNamePrompt : string = "Enter account name for the new password: "
    - <<const>> passwordPrompt : string = "Enter the password: "
    - <<const>> urlPrompt : string = "Enter the URL (optional): "
    - <<const>> categoryPrompt : string = "Enter the category (optional): "
    - <<const>> successMessage : string = "A new password has been created and stored for {0&#125;, {1&#125;."
    + Execute() : void
}
ICommand <|-- CreatePasswordCommand
CreatePasswordCommand o-> "vault" IVault
CreatePasswordCommand o-> "consoleService" IConsole
@enduml
