@startuml
class PasswordUniquenessService {
    + PasswordUniquenessService(vault:IVault)
    + <<async>> IsUniquePasswordAsync(password:string) : Task<bool>
}
IPasswordUniquenessService <|-- PasswordUniquenessService
PasswordUniquenessService --> "_vault" IVault
@enduml
