@startuml
class PasswordHealthResult {
    + IsStrong : bool <<get>>
    + IsUnique : bool <<get>>
    + IsCompromised : bool <<get>>
    + PasswordHealthResult(isStrong:bool, isUnique:bool, isCompromised:bool)
}
@enduml
