@startuml
class PasswordHealthService {
    + PasswordHealthService(passwordStrengthService:IPasswordStrengthService, passwordUniquenessService:IPasswordUniquenessService, compromisedPasswordService:ICompromisedPasswordService)
    + <<async>> CheckPasswordHealthAsync(password:string) : Task<PasswordHealthResult>
}
PasswordHealthService --> "_passwordStrengthService" IPasswordStrengthService
PasswordHealthService --> "_passwordUniquenessService" IPasswordUniquenessService
PasswordHealthService --> "_compromisedPasswordService" ICompromisedPasswordService
@enduml
