@startuml
class DeletePasswordCommand {
    - <<readonly>> serviceNamePrompt : string = "Enter the service name for the password you want to delete: "
    - <<readonly>> accountNamePrompt : string = "Enter the account name for the password you want to delete: "
    - <<readonly>> successMessage : string = "Password entry has been deleted."
    - <<readonly>> errorMessage : string = "Failed to delete the password entry. Ensure the service and account names are correct."
    + Execute() : void
    - GetServiceName() : string
    - GetAccountName() : string
}
ICommand <|-- DeletePasswordCommand
@enduml
