@startuml
class DeleteAllPasswordsCommand {
    - <<readonly>> confirmationPrompt : string = "Are you sure you want to delete all passwords?"
    - <<readonly>> successMessage : string = "All passwords have been deleted."
    - <<readonly>> errorMessage : string = "Operation cancelled."
    + Execute() : void
}
ICommand <|-- DeleteAllPasswordsCommand
@enduml
