@startuml
!include .\\.\src\KeyVaultCli.Presentation\Program.puml
!include .\\.\src\KeyVaultCli.Application\Services\VaultService.puml
!include .\\.\src\KeyVaultCli.Domain\Entities\PasswordEntry.puml
!include .\\.\src\KeyVaultCli.Domain\Entities\Vault.puml
!include .\\.\src\KeyVaultCli.Domain\Exceptions\PasswordNotFoundException.puml
!include .\\.\src\KeyVaultCli.Domain\Factories\PasswordEntryBuilder.puml
!include .\\.\src\KeyVaultCli.Domain\Factories\VaultFactory.puml
!include .\\.\src\KeyVaultCli.Infrastructure\Services\CommandService.puml
!include .\\.\src\KeyVaultCli.Infrastructure\Services\EncryptionService.puml
!include .\\.\src\KeyVaultCli.Infrastructure\Services\FileService.puml
!include .\\.\src\KeyVaultCli.Infrastructure\Services\PasswordGeneratorService.puml
!include .\\.\src\KeyVaultCli.Presentation\Services\ConsoleService.puml
!include .\\.\src\KeyVaultCli.Application\Cli\Commands\ExitCommand.puml
!include .\\.\src\KeyVaultCli.Application\Common\Constants\CommandFlag.puml
!include .\\.\src\KeyVaultCli.Application\Common\Interfaces\ICommand.puml
!include .\\.\src\KeyVaultCli.Application\Common\Interfaces\ICommandService.puml
!include .\\.\src\KeyVaultCli.Application\Common\Interfaces\IConsoleService.puml
!include .\\.\src\KeyVaultCli.Application\Common\Interfaces\IEncryptionService.puml
!include .\\.\src\KeyVaultCli.Application\Common\Interfaces\IFileService.puml
!include .\\.\src\KeyVaultCli.Application\Common\Interfaces\IPasswordGeneratorService.puml
!include .\\.\src\KeyVaultCli.Application\Common\Interfaces\IVaultService.puml
!include .\\.\src\KeyVaultCli.Domain\Common\Interfaces\IConsole.puml
!include .\\.\src\KeyVaultCli.Domain\Common\Interfaces\IVault.puml
!include .\\.\src\KeyVaultCli.Domain\Common\Interfaces\IVaultEncryptionService.puml
!include .\\.\src\KeyVaultCli.Domain\Common\Interfaces\IVaultFactory.puml
!include .\\.\src\KeyVaultCli.Domain\Common\Interfaces\IVaultFileService.puml
!include .\\.\src\KeyVaultCli.Domain\Common\Interfaces\IVaultPasswordGenerator.puml
!include .\\.\src\KeyVaultCli.Presentation\UserInterface\Table\Alignment.puml
!include .\\.\src\KeyVaultCli.Presentation\UserInterface\Table\ConsoleTable.puml
!include .\\.\src\KeyVaultCli.Presentation\UserInterface\Table\ConsoleTableOptions.puml
!include .\\.\src\KeyVaultCli.Presentation\UserInterface\Table\Format.puml
!include .\\.\src\KeyVaultCli.Application\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\.\src\KeyVaultCli.Application\obj\Debug\net7.0\KeyVaultCli.Application.AssemblyInfo.puml
!include .\\.\src\KeyVaultCli.Application\obj\Debug\net7.0\KeyVaultCli.Application.GlobalUsings.g.puml
!include .\\.\src\KeyVaultCli.Application\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\src\KeyVaultCli.Application\obj\Debug\net8.0\KeyVaultCli.Application.AssemblyInfo.puml
!include .\\.\src\KeyVaultCli.Application\obj\Debug\net8.0\KeyVaultCli.Application.GlobalUsings.g.puml
!include .\\.\src\KeyVaultCli.Application\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\src\KeyVaultCli.Application\obj\Release\net8.0\KeyVaultCli.Application.AssemblyInfo.puml
!include .\\.\src\KeyVaultCli.Application\obj\Release\net8.0\KeyVaultCli.Application.GlobalUsings.g.puml
!include .\\.\src\KeyVaultCli.Application\PasswordEntry\Commands\CreatePasswordEntry\CreatePasswordCommand.puml
!include .\\.\src\KeyVaultCli.Application\PasswordEntry\Commands\CreatePasswordEntry\CreatePasswordGeneratedCommand.puml
!include .\\.\src\KeyVaultCli.Application\PasswordEntry\Commands\DeletePasswordEntry\DeleteAllPasswordsCommand.puml
!include .\\.\src\KeyVaultCli.Application\PasswordEntry\Commands\DeletePasswordEntry\DeletePasswordCommand.puml
!include .\\.\src\KeyVaultCli.Application\PasswordEntry\Commands\GetPasswordEntry\GetAllPasswordsCommand.puml
!include .\\.\src\KeyVaultCli.Application\PasswordEntry\Commands\GetPasswordEntry\GetPasswordCommand.puml
!include .\\.\src\KeyVaultCli.Application\PasswordEntry\Commands\GetPasswordEntry\SearchPasswordEntriesCommand.puml
!include .\\.\src\KeyVaultCli.Application\PasswordEntry\Commands\UpdatePasswordEntry\UpdateMasterPasswordCommand.puml
!include .\\.\src\KeyVaultCli.Application\PasswordEntry\Commands\UpdatePasswordEntry\UpdatePasswordCommand.puml
!include .\\.\src\KeyVaultCli.Application\PasswordEntry\Commands\UpdatePasswordEntry\UpdatePasswordGeneratedCommand.puml
!include .\\.\src\KeyVaultCli.Application\Vault\Commands\CreateVault\CreateVaultCommand.puml
!include .\\.\src\KeyVaultCli.Application\Vault\Commands\DeleteVault\DeleteVaultCommand.puml
!include .\\.\src\KeyVaultCli.Domain\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\.\src\KeyVaultCli.Domain\obj\Debug\net7.0\KeyVaultCli.Domain.AssemblyInfo.puml
!include .\\.\src\KeyVaultCli.Domain\obj\Debug\net7.0\KeyVaultCli.Domain.GlobalUsings.g.puml
!include .\\.\src\KeyVaultCli.Domain\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\src\KeyVaultCli.Domain\obj\Debug\net8.0\KeyVaultCli.Domain.AssemblyInfo.puml
!include .\\.\src\KeyVaultCli.Domain\obj\Debug\net8.0\KeyVaultCli.Domain.GlobalUsings.g.puml
!include .\\.\src\KeyVaultCli.Domain\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\src\KeyVaultCli.Domain\obj\Release\net8.0\KeyVaultCli.Domain.AssemblyInfo.puml
!include .\\.\src\KeyVaultCli.Domain\obj\Release\net8.0\KeyVaultCli.Domain.GlobalUsings.g.puml
!include .\\.\src\KeyVaultCli.Infrastructure\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\.\src\KeyVaultCli.Infrastructure\obj\Debug\net7.0\KeyVaultCli.Infrastructure.AssemblyInfo.puml
!include .\\.\src\KeyVaultCli.Infrastructure\obj\Debug\net7.0\KeyVaultCli.Infrastructure.GlobalUsings.g.puml
!include .\\.\src\KeyVaultCli.Infrastructure\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\src\KeyVaultCli.Infrastructure\obj\Debug\net8.0\KeyVaultCli.Infrastructure.AssemblyInfo.puml
!include .\\.\src\KeyVaultCli.Infrastructure\obj\Debug\net8.0\KeyVaultCli.Infrastructure.GlobalUsings.g.puml
!include .\\.\src\KeyVaultCli.Infrastructure\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\src\KeyVaultCli.Infrastructure\obj\Release\net8.0\KeyVaultCli.Infrastructure.AssemblyInfo.puml
!include .\\.\src\KeyVaultCli.Infrastructure\obj\Release\net8.0\KeyVaultCli.Infrastructure.GlobalUsings.g.puml
!include .\\.\src\KeyVaultCli.Presentation\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\.\src\KeyVaultCli.Presentation\obj\Debug\net7.0\KeyVaultCli.Presentation.AssemblyInfo.puml
!include .\\.\src\KeyVaultCli.Presentation\obj\Debug\net7.0\KeyVaultCli.Presentation.GlobalUsings.g.puml
!include .\\.\src\KeyVaultCli.Presentation\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\src\KeyVaultCli.Presentation\obj\Debug\net8.0\KeyVaultCli.Presentation.AssemblyInfo.puml
!include .\\.\src\KeyVaultCli.Presentation\obj\Debug\net8.0\KeyVaultCli.Presentation.GlobalUsings.g.puml
!include .\\.\src\KeyVaultCli.Presentation\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\src\KeyVaultCli.Presentation\obj\Release\net8.0\KeyVaultCli.Presentation.AssemblyInfo.puml
!include .\\.\src\KeyVaultCli.Presentation\obj\Release\net8.0\KeyVaultCli.Presentation.GlobalUsings.g.puml
@enduml
