@startuml
class PasswordGeneratorService {
    <<const>> - lowerCase : string = "abcdefghijklmnopqrstuvwxyz"
    <<const>> - upperCase : string = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    <<const>> - digits : string = "1234567890"
    <<const>> - specialCharacters : string = "!@#$%^&*_-+=:;<>?/"
    + GeneratePassword(length:int) : string
    - {static} GetRandomNumber(rng:System.Security.Cryptography.RNGCryptoServiceProvider, max:int) : int
}
IPasswordGeneratorService <|-- PasswordGeneratorService
@enduml
