@startuml
class UpdatePasswordCommand {
    - <<readonly>> currentServiceNamePrompt : string = "Enter current service name: "
    - <<readonly>> currentAccountNamePrompt : string = "Enter current account name: "
    - <<readonly>> newServiceNamePrompt : string = "Enter new service name: "
    - <<readonly>> newAccountNamePrompt : string = "Enter new account name: "
    - <<readonly>> newPasswordPrompt : string = "Enter new password: "
    - <<readonly>> newUrlPrompt : string = "Enter new URL: "
    - <<readonly>> newCategoryPrompt : string = "Enter new Category: "
    - <<readonly>> successMessage : string = "The password entry has been updated."
    - <<readonly>> errorMessage : string = "Failed to update the password entry. Ensure the service and account exists."
    + Execute() : void
}
ICommand <|-- UpdatePasswordCommand
UpdatePasswordCommand o-> "vault" IVault
UpdatePasswordCommand o-> "consoleService" IConsoleService
@enduml
