@startuml
class UpdateMasterPasswordCommand {
    - <<readonly>> oldPasswordPrompt : string = "Enter current master password: "
    - <<readonly>> newPasswordPrompt : string = "Enter new master password: "
    - <<readonly>> successMessage : string = "Master password has been updated."
    - <<readonly>> errorMessage : string = "No need to update you entered the same passwords."
    + Execute() : void
}
ICommand <|-- UpdateMasterPasswordCommand
UpdateMasterPasswordCommand o-> "vault" IVault
UpdateMasterPasswordCommand o-> "consoleService" IConsoleService
@enduml
