@startuml
class UpdatePasswordGeneratedCommand {
    - <<readonly>> oldServiceNamePrompt : string = "Enter old service name: "
    - <<readonly>> oldAccountNamePrompt : string = "Enter old account name: "
    - <<readonly>> newServiceNamePrompt : string = "Enter new service name: "
    - <<readonly>> newAccountNamePrompt : string = "Enter new account name: "
    - <<readonly>> newUrlPrompt : string = "Enter new URL: "
    - <<readonly>> newCategoryPrompt : string = "Enter new Category: "
    - <<readonly>> passwordLengthPrompt : string = "Enter the number of characters for the new password (e.g. 10): "
    - <<readonly>> invalidLengthError : string = "Invalid input for password length. Ensure you enter a valid number."
    - <<readonly>> successMessage : string = "Password entry for {0&#125;, {1&#125; has been updated with new details."
    - <<readonly>> errorMessage : string = "Failed to update the password entry. Ensure the old service and account names are correct."
    + Execute() : void
}
ICommand <|-- UpdatePasswordGeneratedCommand
@enduml
