@startuml
class VaultService {
    + VaultService(vaultConsoleService:IConsole, vaultEncryptionService:IVaultEncryptionService, vaultFileService:IVaultFileService, vaultPasswordGenerator:IVaultPasswordGenerator)
    + CreateVault(masterPassword:string) : IVault?
    + DeleteVault() : bool
    + GetVault() : IVault
}
IVaultService <|-- VaultService
VaultService --> "_vaultConsoleService" IConsole
VaultService --> "_vaultEncryptionService" IVaultEncryptionService
VaultService --> "_vaultFileService" IVaultFileService
VaultService --> "_vaultPasswordGenerator" IVaultPasswordGenerator
VaultService --> "_vaultFactory" VaultFactory
@enduml
