@startuml
class RestoreVaultCommand {
    - <<readonly>> restoreSuccessMsg : string = "  ____           _                     _ \n |  _ \\ ___  ___| |_ ___  _ __ ___  __| |\n | |_) / _ \\/ __| __/ _ \\| '__/ _ \\/ _` |\n |  _ <  __/\\__ \\ || (_) | | |  __/ (_| |\n |_| \\_\\___||___/\\__\\___/|_|  \\___|\\__,_|\n                                         "
    - confirmationPrompt : string = "Are you sure you want to restore the vault?"
    - filePathPrompt : string = "Enter the full path to the backup file: "
    - <<readonly>> restoreErrorMsg : string = "Failed to restore vault."
    - <<readonly>> operationCancelMsg : string = "Operation cancelled."
    + RestoreVaultCommand(vault:IVault, consoleService:IConsoleService)
    + Execute() : void
    - PerformRestore() : void
}
ICommand <|-- RestoreVaultCommand
RestoreVaultCommand --> "vault" IVault
RestoreVaultCommand --> "consoleService" IConsoleService
@enduml
