@startuml
class PasswordEntry {
    + ServiceName : string <<get>> <<set>>
    + AccountName : string <<get>> <<set>>
    + EncryptedPassword : string <<get>> <<set>>
    + Url : string <<get>> <<set>>
    + Category : string <<get>> <<set>>
    + PasswordEntry()
    + UpdateServiceName(newServiceName:string) : void
    + UpdateAccountName(newAccountName:string) : void
    + UpdateUrl(newUrl:string) : void
    + UpdateCategory(newCategory:string) : void
    + UpdateEncryptedPassword(newPassword:string) : void
    - UpdateLastModifiedDate() : void
}
PasswordEntry --> "EntryId" Guid
PasswordEntry --> "CreationDate" DateTime
PasswordEntry --> "LastModifiedDate" DateTime
@enduml
