@startuml
class Vault {
    - _masterPassword : string
    - <<readonly>> _passwordEntryFilePath : string
    - <<readonly>> _masterPasswordFilePath : string
    + Vault(vaultParams:VaultParams)
    + AddEntryToPasswordList(serviceName:string, accountName:string, password:string, url:string, category:string) : void
    + DecryptAndRetrievePassword(serviceName:string, accountName:string) : string
    + UpdateAndSavePasswordEntry(currentServiceName:string, currentAccountName:string, newServiceName:string, newAccountName:string, passwordLength:int, newPassword:string?, newUrl:string?, newCategory:string?) : bool
    + GeneratePasswordAndAddEntry(serviceName:string, accountName:string, passwordLength:int, url:string, category:string) : string
    + SaveMasterPassword() : void
    + LoadMasterPassword() : string?
    + UpdateMasterPassword(oldPassword:string, newPassword:string) : bool
    + SavePasswordEntries() : void
    + DeletePasswordEntry(serviceName:string, accountName:string) : bool
    + DeleteAllPasswordEntries() : void
    + LoadPasswordEntries() : List<PasswordEntry>
    + GetAllDecryptedPasswords() : Dictionary<string, string>
    + GetPasswordEntry(serviceName:string, accountName:string) : PasswordEntry?
    + SearchPasswordEntries(searchTerm:string) : List<PasswordEntry>
    + BackupVault(backupFilePath:string) : bool
    + RestoreVault(backupFilePath:string) : bool
}
class "List`1"<T> {
}
IVault <|-- Vault
Vault --> "_passwordEntries<PasswordEntry>" "List`1"
Vault --> "_vaultEncryptionService" IVaultEncryptionService
Vault --> "_vaultFileService" IVaultFileService
Vault --> "_vaultPasswordGenerator" IVaultPasswordGenerator
@enduml
